<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
    <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
        <%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
            <!DOCTYPE html>
            <html>

            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Calendar - Task Manager</title>
                <link rel="stylesheet" href="css/style.css">
                <style>
                    .calendar-container {
                        background-color: var(--card-bg);
                        border-radius: 12px;
                        padding: 2rem;
                        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
                    }

                    .calendar-header {
                        display: flex;
                        justify-content: space-between;
                        align-items: center;
                        margin-bottom: 2rem;
                    }

                    .calendar-grid {
                        display: grid;
                        grid-template-columns: repeat(7, 1fr);
                        gap: 10px;
                    }

                    .calendar-day-header {
                        text-align: center;
                        font-weight: bold;
                        color: var(--secondary-text);
                        padding: 10px;
                    }

                    .calendar-day {
                        background-color: var(--input-bg);
                        border-radius: 8px;
                        min-height: 80px;
                        padding: 10px;
                        position: relative;
                        border: 1px solid var(--border-color);
                    }

                    .calendar-day.today {
                        border-color: var(--accent-color);
                    }

                    .day-number {
                        font-weight: bold;
                        margin-bottom: 5px;
                        display: block;
                    }

                    .task-dot {
                        display: block;
                        background-color: var(--accent-color);
                        color: #000;
                        font-size: 0.7rem;
                        padding: 2px 4px;
                        border-radius: 4px;
                        margin-bottom: 2px;
                        white-space: nowrap;
                        overflow: hidden;
                        text-overflow: ellipsis;
                        cursor: pointer;
                    }

                    .task-dot.completed {
                        background-color: rgba(0, 230, 118, 0.5);
                        color: #fff;
                        text-decoration: line-through;
                    }

                    .task-dot.overdue {
                        background-color: var(--danger-color);
                        color: #fff;
                    }

                    @media (max-width: 768px) {
                        .calendar-grid {
                            gap: 4px;
                        }
                        .calendar-day {
                            min-height: 50px;
                            padding: 6px 4px;
                        }
                        .day-number {
                            font-size: 0.8rem;
                        }
                        .task-dot {
                            font-size: 0.6rem;
                            padding: 1px 2px;
                        }
                    }
                </style>
            </head>

            <body>
                <nav class="navbar">
                    <div class="nav-brand">Task Manager</div>
                    <div class="nav-links">
                        <a href="dashboard">Dashboard</a>
                        <a href="calendar" class="active" style="color: var(--accent-color);">Calendar</a>
                        <a href="logout">Logout</a>
                    </div>
                </nav>

                <div class="container" style="margin-top: 2rem;">
                    <div class="calendar-container">
                        <div class="calendar-header">
                            <button class="btn btn-sm btn-primary" onclick="changeMonth(-1)">&lt; Prev</button>
                            <h2 id="monthYear"></h2>
                            <button class="btn btn-sm btn-primary" onclick="changeMonth(1)">Next &gt;</button>
                        </div>

                        <div class="calendar-grid" id="calendarGrid">
                            <!-- Days will be generated by JS -->
                        </div>
                    </div>
                </div>

                <script>
                    // Pass tasks from JSP to JS
                    const tasks = [
                        <c:forEach items="${tasks}" var="task" varStatus="status">
                            {
                                id: ${task.id},
                                title: "${task.title}",
                                date: "${task.dueDate}",
                                status: "${task.status}",
                                hasTime: ${task.hasTime}
                            }${status.last ? '' : ','}
                        </c:forEach>
                    ];

                    let currentDate = new Date();

                    function renderCalendar() {
                        const monthYear = document.getElementById('monthYear');
                        const calendarGrid = document.getElementById('calendarGrid');

                        const year = currentDate.getFullYear();
                        const month = currentDate.getMonth();

                        const firstDay = new Date(year, month, 1);
                        const lastDay = new Date(year, month + 1, 0);
                        const daysInMonth = lastDay.getDate();
                        const startingDay = firstDay.getDay(); // 0 = Sunday

                        const monthNames = ["January", "February", "March", "April", "May", "June",
                            "July", "August", "September", "October", "November", "December"
                        ];

                        monthYear.textContent = monthNames[month] + " " + year;
                        calendarGrid.innerHTML = "";

                        // Day Headers
                        const days = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
                        days.forEach(day => {
                            const div = document.createElement('div');
                            div.className = 'calendar-day-header';
                            div.textContent = day;
                            calendarGrid.appendChild(div);
                        });

                        // Empty slots before first day
                        for (let i = 0; i < startingDay; i++) {
                            const div = document.createElement('div');
                            div.className = 'calendar-day';
                            div.style.visibility = 'hidden';
                            calendarGrid.appendChild(div);
                        }

                        // Days
                        const today = new Date();
                        for (let i = 1; i <= daysInMonth; i++) {
                            const div = document.createElement('div');
                            div.className = 'calendar-day';

                            // Check if today
                            if (year === today.getFullYear() && month === today.getMonth() && i === today.getDate()) {
                                div.classList.add('today');
                            }

                            const dayNum = document.createElement('span');
                            dayNum.className = 'day-number';
                            dayNum.textContent = i;
                            div.appendChild(dayNum);

                            // Find tasks for this day
                            const dateStr = year + "-" + String(month + 1).padStart(2, '0') + "-" + String(i).padStart(2, '0');
                            
                            const now = new Date();
                            const nowStr = now.getFullYear() + "-" + 
                                             String(now.getMonth() + 1).padStart(2, '0') + "-" + 
                                             String(now.getDate()).padStart(2, '0') + "T" +
                                             String(now.getHours()).padStart(2, '0') + ":" +
                                             String(now.getMinutes()).padStart(2, '0');

                            tasks.forEach(task => {
                                const taskDateOnly = task.date.substring(0, 10);
                                if (taskDateOnly === dateStr) {
                                    const taskDiv = document.createElement('div');
                                    taskDiv.className = 'task-dot';
                                    
                                    if (task.status === 'Completed') {
                                        taskDiv.classList.add('completed');
                                    } else {
                                        if (task.hasTime) {
                                            const taskTime = task.date.substring(0, 16).replace(' ', 'T');
                                            if (taskTime < nowStr) {
                                               taskDiv.classList.add('overdue');
                                            }
                                        } else {
                                            if (taskDateOnly < nowStr.substring(0, 10)) {
                                                taskDiv.classList.add('overdue');
                                            }
                                        }
                                    }
                                    
                                    let timeLabel = "";
                                    if (task.hasTime) {
                                        timeLabel = " (" + task.date.substring(11, 16) + ")";
                                    }
                                    
                                    taskDiv.textContent = task.title + timeLabel;
                                    taskDiv.title = task.title + (task.hasTime ? " @ " + task.date.substring(11, 16) : "");
                                    div.appendChild(taskDiv);
                                }
                            });

                            calendarGrid.appendChild(div);
                        }
                    }

                    function changeMonth(delta) {
                        currentDate.setMonth(currentDate.getMonth() + delta);
                        renderCalendar();
                    }

                    // Initial render
                    renderCalendar();
                </script>
            </body>

            </html>